### ISSUE TITLE
Metamask SDK is super slow on React Native, while it's fast with apps like Minter Guru

### ISSUE THREAD

**Issue by mohammed-io** [MetaMask/metamask-sdk#237]
**Describe the bug**

We are integrating MetaMask SDK into our app. However, we noticed that it's not reliable at all; sometimes it works (still too slow slow), and sometimes it takes forever to connect (and the app will be killed after 2 minutes in the background).

I don't understand the underlying problem behind that performance issue, we tried to multiple geographical locations in the world, seems to be the same problem. I also tried to user another communication layer like WebRTC and toggle between `transports: ['polling']` and `transports: ['websocket']` but with no result.

I also tried to see if Minter Guru uses another endpoint than `https://metamask-sdk-socket.metafi.codefi.network`, but that wasn't the case, there's no alternative to this endpoint.

I also toggled `developerMode` and `enableDebug` in case they have some "overhead", and all got the same result.

I suspect somehow the socket connection is slow and not sending the messages quickly, but it's just guessing, and I have no way to validate that; the code is minified and not easy to debug.

**To Reproduce**
1. Clone and install the sample https://github.com/thulasiram-polygon/ReactNative-Web3-Demo
2. Click on 'Connect to MetaMask'
3. It takes so long to complete the request (and sometimes it never finishes)

The same with the demo provided at https://c0f4f41c-2f55-4863-921b-sdk-docs.github.io/guide/metamask-sdk-js/metamask-sdk-react-native.html, although the WebView version doesn't work.

**Expected behaviour**
To be reliable and at a speed comparable to Minter Guru.

**Screenshots**

When using the SDK, it took so long to have the first direct (and still got stuck at the last step; sometimes it connects successfully), The metamask SDK:
https://github.com/MetaMask/metamask-sdk/assets/18808136/fd482d3e-a187-4b89-b7bc-50948a89cb13

While with Minter Guru, there's not even a loading modal, with Minter Guru:
https://github.com/MetaMask/metamask-sdk/assets/18808136/ce8aef87-1e99-4585-aa36-2ccfe55605d0

** Provide environment information**
- Platform (Eg. Web / React-Native / Node.js / Unity): React Native
- MetaMask SDK Version: 0.5.3
- MetaMask Mobile Version: 7.3.0
- Browser (if relevant):

**Additional context**
I tried with the sample code projects provided to make sure there's no other dependency in our app causing that.

**Comment by christopherferreira9** [comment]
Hi @mohammed-io ! 
We're currently working on improving the socket connection and it should be released in the coming weeks.
Depending on the ReactNative version the encryption layer performance varies drastically in performance. This doesn't necessarily relate to connection popup showing or not  but it relates to the speed with which the messages are exchanged between Dapp and MetaMask Mobile Wallet (which in the end affect the speed at which messages are exchanged).
We're currently using RN version 0.71.7 in our examples and this versions is considerably faster than the previous versions. Keep in mind that there are some performance differences between iOS and Android as well.

Can you take a look at our [RN example](https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/reactNativeDemo) instead of the documentation one?
Thank you for reporting!
