### ISSUE TITLE
[Bug]: DeepLink not working on desktop

### ISSUE THREAD

**Issue by xcaptain** [MetaMask/metamask-sdk#785]
### SDK

Web

### Provide environment information

windows 11, edge browser, metamask extension installed

### MetaMask SDK Version

no

### MetaMask Mobile app Version

no

### What browser are you using? (if relevant)

edge

### Describe the Bug

I generated a deeplink: https://metamask.app.link/dapp/opensea.io/collection/follow-the-white-rabbit-7

open on mobile device is ok, will open in metamask mobile app
But open on desktop browser like edge, I was  redirected to https://metamask.io/download

### Expected Behavior

I think the correct redirect url should be https://opensea.io/collection/follow-the-white-rabbit-7

The server should know if the user is using desktop or mobile device

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://metamask.app.link/dapp/opensea.io/collection/follow-the-white-rabbit-7

### To Reproduce

open the deeplink on desktop browser

**Comment by christopherferreira9** [comment]
Hi @xcaptain !
Deeplinks are made to work with MetaMask Mobile to ease the use of the Mobile Wallet when the SDK is not in use and not with the extension. 
What we can suggest is the usage of the [MetaMask SDK](https://github.com/MetaMask/metamask-sdk) which will allow you to connect both MetaMask mobile via direct deeplink (when using a mobile browser) instead of the inapp browser or connect using the browser desktop with a QRCode that the mobile scans or MetaMask Extension.

**Comment by xcaptain** [comment]
I think it's easy to make the deeplink open metamask when use a phone and jump to target dapp url when using a desktop computer, just simple user agent checks.

This feature is important, for example I share a deeplink to telegram, all the user should just to my dapp website rather than metamask download page
