### ISSUE TITLE
[Bug]: Chrome android connect and switch network in the same iteraction

### ISSUE THREAD

**Issue by andremfaria** [MetaMask/metamask-sdk#847]
### SDK

Web

### Provide environment information

Android: 14
Chrome Android: 123.0.6312.100
MetaMask mobile app: 7.19.1 (1306)

### MetaMask SDK Version

0.18.6

### MetaMask Mobile app Version

7.19.1 (1306)

### What browser are you using? (if relevant)

Chrome Android: 123.0.6312.100

### Describe the Bug

When using Chrome, if we connect MetaMask and perform some logic, then call `wallet_switchEthereumChain`, the web app fails to display the information prompting us to navigate to the wallet. Instead, we must manually switch to the MetaMask app. Additionally, if we accept, it does not return to the web browser.

In Firefox for Android, it exhibits the expected behavior. Moreover, I tested it on iOS with Safari, and it functions normally.

https://github.com/MetaMask/metamask-sdk/assets/10519908/ebe8e6da-ff4b-448e-a3e9-b987646edc27

https://github.com/MetaMask/metamask-sdk/assets/10519908/11347b74-9de0-4c06-b54e-a2090bc4d69c

### Expected Behavior

(similar to Firefox video)

1. Connect with `sdk?.connect()` and back to the web app. 
2. Show the user the info task if they want to proceed to the wallet app. 
3. Accept the switch network. 
4. Back to the web app

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/andremfaria/mm-switch-network-after-connect

### To Reproduce

Run the provided code and access it with Google Chrome on Android.
Ensure that you have a different network selected from Ethereum 0x1.

**Comment by christopherferreira9** [comment]
Hi @andremfaria ! The behaviour is the expected one but we have a custom RPC that will provide the experience you want! 
You can use directly connectWith like:
```typescript
const switchChainRPC = {
    method: 'wallet_switchEthereumChain',
    params: [{
        chainId: '0x1'  // or any other chainId you might want to switch to
    }]
}
const response = sdk?.connectWith(switchChainRPC)
```
This will do 2 things:
- Ask the user to connect
- Ask the user to switch chain

This means that while using android, it'll only send the user back after accepting or denying the switchChain request. 
Generically speaking, it is not advised that while using the MMSDK to dynamically or programatically perform requests that will require the user input as the phone operative system may block this automated behaviour. This is also the reason why it currently works in Firefox like you just shown since it is asking for an explicit input to trigger the deeplink.

I'm closing this issue but please feel free to open any other issue you experience.
