### ISSUE TITLE
[Bug]: Mobile - Redirect to install MetaMask fails When Deeplink is True and Metamask is Not Installed

### ISSUE THREAD

**Issue by andremfaria** [MetaMask/metamask-sdk#950]
### SDK

Web

### Provide environment information

webapp

### MetaMask SDK Version

v0.26.4

### MetaMask Mobile app Version

Not applicable

### What browser are you using? (if relevant)

Chrome 126.0.6478.122 (android)

### Describe the Bug

When MetaMask mobile is not installed and we try to connect, the app fails to redirect to the install page. This issue occurs only when `useDeepLink=true.`

In the video, I reproduced the issue on Android. I also tested it on Safari on iOS, and it doesn't work there either and prompts a `"Safari cannot open the page because the address is invalid"` error.

https://github.com/user-attachments/assets/97b01c14-ccc4-4e40-bb1a-399bb72a5682

### Expected Behavior

The app should properly redirect to the MetaMask installation.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

[mm-sdk-install-problem](https://github.com/andremfaria/mm-sdk-install-problem)

### To Reproduce

You should not have the MetaMask app installed on your smartphone.
To reproduce you can use the following code: https://github.com/andremfaria/mm-sdk-install-problem

**Comment by andreahaku** [comment]
@andremfaria `useDeeplink` is a property that forces the SDK to use deeplinks URI schema instead of universal links. Universal links are able to redirect the user to the app stores if the MM mobile app is not installed. A deeplink URI schema like the one used for Metamask (`metamask://`) is not able to use that and this is the main reason to use Universal links vs deeplinks.
So if you set `useDeeplink=true` and the MM mobile app is not installed, the deeplink fails silently. So what you are describing is the expected behaviour.
